name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libopenblas-dev

      - name: Configure and Build (RELEASE)
        run: |
          cmake -S . -B build -DBUILD_CONFIGURATION=RELEASE -DPRECISION=SINGLE
          cmake --build build
