name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-openmp:
    name: Build with OpenMP
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake gcc libopenblas-dev

      - name: Configure and Build (OpenMP - Release)
        run: |
          CC=gcc cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DPRECISION=SINGLE
          cmake --build build

  build-opencilk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get latest OpenCilk Linux release URL
        id: get_release
        run: |
          release_info=$(curl -s https://api.github.com/repos/OpenCilk/opencilk-project/releases/latest)
          url=$(echo "$release_info" | jq -r '.assets[] | select(.name | test("Linux.*\\.tar\\.gz$")) | .browser_download_url')
          echo "tarball_url=$url" >> $GITHUB_OUTPUT

      - name: Download and extract OpenCilk
        run: |
          wget -q ${{ steps.get_release.outputs.tarball_url }} -O opencilk.tar.gz
          tar -xzf opencilk.tar.gz

      - name: Add OpenCilk to PATH
        # Adjust folder name if needed, assuming extracted folder starts with 'OpenCilk-'
        run: echo "$(pwd)/OpenCilk-*/bin" >> $GITHUB_PATH

      - name: Verify OpenCilk clang version
        run: clang --version

      - name: Build with OpenCilk clang
        run: |
          mkdir build
          CC=clang cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DPRECISION=SINGLE -DUSE_OPENCILK=ON
          cmake --build build

