name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libopenblas-dev libhdf5-dev python3 python3-pip

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Configure and Build (Debug)
        run: |
          CC=gcc cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run Tests
        run: |
          cd tests
          chmod +x run_tests.sh
          ./run_tests.sh
