name: Valgrind

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  valgrind:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libopenblas-dev libhdf5-dev python3 python3-pip valgrind

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Configure and Build (Debug)
        run: |
          CC=gcc cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run Valgrind
        run: |
          cd valgrind
          chmod +x run_valgrind.sh
          ./run_valgrind.sh

      - name: Upload Valgrind Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: valgrind-logs
          path: valgrind/valgrind_*.log
